### ISSUE TITLE
Can't seem to add a proper install page like the Rails app.

### ISSUE THREAD

**Issue by cbodtorf** [Shopify/shopify-app-node#132]
# Issue summary
- related to [`@shopify/koa-shopify-auth`](https://github.com/Shopify/quilt/tree/master/packages/koa-shopify-auth)

Would like a little guidance on setting up a proper login/install page like the Rails app.
It seems like auth is run on every server call, and I can't seem to figure out a way around this.
I may not fully understand the middleware you have running.

Doesn't look like we have control over the `/auth` page or the ability to overwrite that route or managed redirects here.

Would love some insight or examples of how this is expected to be handled.

**Comment by gil--** [comment]
@cbodtorf you could add a new /install route [BEFORE createShopifyAuth](https://github.com/Shopify/shopify-app-node/blob/master/server/server.js#L24):

```js
server.use(
        createShopifyAuth({
```:

Within `./servers/server.js`:

```js
router.get("/install", async ctx => {
    await handle(ctx.req, ctx.res);
});
```

Then add a fallback route within [**verifyRequest**](https://github.com/Shopify/shopify-app-node/blob/master/server/server.js#L46):

```js
verifyRequest({
  fallbackRoute: "/install"
}),
```

And finally, either return content within the Koa response or with the above code, create a new `./pages/install.js` which should load whenever someone goes to your app without having a session or by typing **/install**.
