### ISSUE TITLE
Add RoutePropagator Component?

### ISSUE THREAD

**Issue by gil--** [Shopify/shopify-app-node#148]
# Issue summary

Can I open a PR to add the RoutePropagator component given the experience is embedded by default?

## Expected behavior

Embedded apps should update the url bar and embedded app toolbar links should not cause a full-page refresh. Would be nice to have this OOB by default.

## Actual behavior

Currently, url bar does not update when navigating client-side and embedded app toolbar links cause full-page refresh.

#### RoutePropagator.js

```js
import { RoutePropagator as ShopifyRoutePropagator } from "@shopify/react-shopify-app-route-propagator";
import { Context as AppBridgeContext } from "@shopify/app-bridge-react";
import { Redirect } from "@shopify/app-bridge/actions";
import Router, { useRouter } from "next/router";

const RoutePropagator = () => {
  const router = useRouter();
  const { route } = router;
  const appBridge = React.useContext(AppBridgeContext);

  useEffect(() => {
    appBridge.subscribe(Redirect.ActionType.APP, ({ path }) => {
      Router.push(path);
    });
  }, []);

  return appBridge && route ? (
    <ShopifyRoutePropagator location={route} app={appBridge} />
  ) : null;
}

export default RoutePropagator;
```

#### _app.js 

```js
<Provider
  config={{
    apiKey: API_KEY,
    shopOrigin: shopOrigin,
    forceRedirect: true
  }}
>
  <RoutePropogator />
  <Component {...pageProps} />     
</Provider>
```

**Comment by katiedavis** [comment]
Hi @gil--  Please feel free to open a PR anytime! We love contributions! We can discuss any concerns there :)
