### ISSUE TITLE
Update session to include samesite setting

### ISSUE THREAD

**Issue by carlosreyes** [Shopify/shopify-app-node#201]
# Issue summary

With the updates to chrome's security policies the app's session will need to include the sameSite setting: https://help.shopify.com/en/api/guides/samesite-cookies

## Expected behavior

What do you think should happen?

Samesite settings are included out of the box as apps built with this boilerplate are embedded out of the box as far as I can tell

## Actual behavior

What actually happens?

Users have to have awareness of the issue and be able to dig through documentation to resolve

Potential proposed resolution:
https://github.com/Shopify/quilt/pull/1227/commits/c71b7de340887d49b60470ad93720a046bc9b30b#diff-bc1e64c7a3f21c973926784c63f6b22d

Implement that line of code within the `shopify-node-app` boilerplate as opposed to being buried in a comment in a dependency (and with the monorepo set up of quilt it is difficult to find, IMO)

I will have more time next week to attempt a PR for the issue, but given the Feb 4th deadline, it might be useful to prioritise this earlier. Any comments or thoughts would be appreciated - I've yet to test or implement this, so apologies for that but thought I'd flag it early regardless.

**Comment by katiedavis** [comment]
hi @carlosreyes ! We have plans to implement this today :) Thanks for opening the issue I'll ping you when it's finished.
