### ISSUE TITLE
Issues when running shopify start serve bash

### ISSUE THREAD

**Issue by theoldbarn** [Shopify/shopify-app-node#247]
# Issue summary

Write a short description of the issue here ↓
As the title explains. When I run the 'Shopify start serve' bash command, I get the following error messages:

`> shopify-node-app@1.0.0 dev /Users/Tom/eagle
┃ > NODE_ENV=development nodemon ./server/index.js --watch ./server/index.js
┃ 
┃ [nodemon] 2.0.2
┃ [nodemon] to restart at any time, enter `rs`
┃ [nodemon] watching dir(s): server/index.js
┃ [nodemon] watching extensions: js,mjs,json
┃ [nodemon] starting `node ./server/index.js`
┃ Browserslist: caniuse-lite is outdated. Please run next command `npm update`
npm update
┃ events.js:288
┃       throw er; // Unhandled 'error' event
┃       ^
┃ 
┃ Error: listen EADDRINUSE: address already in use :::8081
┃     at Server.setupListenHandle [as _listen2] (net.js:1309:16)
┃     at listenInCluster (net.js:1357:12)
┃     at Server.listen (net.js:1445:7)
┃     at Application.listen (/Users/Tom/eagle/node_modules/koa/lib/application.js:80:19)
┃     at /Users/Tom/eagle/server/server.js:63:10
┃     at runMicrotasks (<anonymous>)
┃     at processTicksAndRejections (internal/process/task_queues.js:97:5)
┃ Emitted 'error' event on Server instance at:
┃     at emitErrorNT (net.js:1336:8)
┃     at processTicksAndRejections (internal/process/task_queues.js:84:21) {
┃   code: 'EADDRINUSE',
┃   errno: 'EADDRINUSE',
┃   syscall: 'listen',
┃   address: '::',
┃   port: 8081
┃ }
┃ [nodemon] app crashed - waiting for file changes before starting...
`

## Expected behavior

What do you think should happen?
To proceed with the Shopify App Cli set-up and be asked for my Shopify API Key & Secret API Key
## Actual behavior

What actually happens?
Error message: [nodemon] app crashed - waiting for file changes before starting...

Tip: include an error message (in a `<details></details>` tag) if your issue is related to an error

## Steps to reproduce the problem

1. 1. 1.

## Reduced test case

The best way to get your bug fixed is to provide a reduced test case.

## Specifications

- Browser: Chrome
- Device:
- Operating System: Mac High Sierra 10.13.6

**Comment by katiedavis** [comment]
Hello! I just want to make sure you're running `shopify serve` and not `shopify start serve`

It looks like you already having something running on port 8081. You'll need to kill everything running on that port and run `shopify serve` again.

**Comment by theoldbarn** [comment]
Hi!

Thank you for replying to my query!

Having shut everything down, and back on again, I have initiated the `shopify create new project new-project-name`.

Creating the project as a node embedded app.
Cloning went fine.
Installing dependencies with npm went fine.
Run `shopify serve`
Ngrok fine and .env fine
"Do you want to update your url?" yes

Then I run into this issue:
Browserslist: caniuse-lite is outdated. Please run next command `npm update`
> Ready on http://localhost:8081
[ wait ]  compiling ...

Compiling goes on for 10 minutes+

Am I missing something here?

**Comment by theoldbarn** [comment]
Actually, may have fixed it!
Thanks for your help :)
