### ISSUE TITLE
Best practice for using accessing the app bridge context

### ISSUE THREAD

**Issue by dan-gamble** [Shopify/shopify-app-node#40]
# Issue summary

Feel a tad silly with this one as I feel it is actually probably quite simple.

I'm looking to use the `Redirect` from the app-bridge. (`import {Redirect} from '@shopify/app-bridge/actions'`).

The issue I'm having is around the `app` part.

```
app.dispatch(
  Redirect.toRemote({
    url: 'http://example.com',
  }),
)
```

Above it mentions doing:

```
const app = createApp({
  apiKey: '12345',
  shopOrigin: shopOrigin,
});
```

[But given we're already using the `<Provider`](https://github.com/Shopify/shopify-app-node/blob/master/pages/_app.js#L23) I'd imagine this is accessible in `context` somewhere like it used to be?

I've tried going down the `createApp` route but I'm not sure where I should be saving this to have it accessible globally. Given we're using `next` I can't use `window` for example.

Apologies if this is the wrong place to ask this but the app-bridge repos are internal.

**Comment by deepcut** [comment]
Any update on this one? @dan-gamble

**Comment by gil--** [comment]
@deepcut Just do something like this for example (my Route Propagator):

```
import { RoutePropagator as ShopifyRoutePropagator } from "@shopify/react-shopify-app-route-propagator";
import { Context as AppBridgeContext } from "@shopify/app-bridge-react";
import { Redirect } from '@shopify/app-bridge/actions';
import Router, { useRouter } from "next/router";

const RoutePropagator = () => {
  const router = useRouter();
  const { route } = router;
  const appBridge = React.useContext(AppBridgeContext);

  useEffect(() => {
    appBridge.subscribe(Redirect.ActionType.APP, ({ path }) => {
      Router.push(path);
    });
  }, []);

  return appBridge && route ? (
    <ShopifyRoutePropagator location={route} app={appBridge} />
  ) : null;
}

export default RoutePropagator;
```
