### ISSUE TITLE
App Bridge React Link in README Leads to a 404

### ISSUE THREAD

**Issue by DaveLak** [Shopify/shopify-app-node#418]
# Issue summary

The project [README](https://github.com/Shopify/shopify-app-node/blob/master/README.md#L6) contains a link to a repository on GitHub called App Bridge React which does not exist or is private which results in a 404 when followed. 

The broken link is:

```
[App Bridge React](https://github.com/Shopify/app-bridge/tree/master/packages/app-bridge-react)
```

## Expected behavior

The link should lead to a public repository, relevant documentation or be removed.

### Possible Replacement URLs

- https://shopify.dev/tools/app-bridge
- https://shopify.dev/tools/app-bridge/react-components
- https://github.com/Shopify/shopify-app-bridge (though this repository only contains a README at the time of writing)

**Comment by andyw8** [comment]
@DaveLak thanks for reporting this, it's been fixed.
