### ISSUE TITLE
export 'FilterType' was not found in '@shopify/polaris'

### ISSUE THREAD

**Issue by mozeryansky** [Shopify/shopify-app-node#477]
1. `shopify generate page MyPage`
? Which template would you like to use? (You chose: list)

When I vist my page it then says:
`export 'FilterType' was not found in '@shopify/polaris'`

**Comment by paulomarg** [comment]
Hi @mozeryansky, thank you for reporting this. We will look into it!

**Comment by mozeryansky** [comment]
I believe this was caused because I updated my react dependency to "^17". The error goes away when I go back to "^16".

**Comment by Xardasus** [comment]
Hi guys, The issue still there, no changes have been made to anything

**Comment by mllemango** [comment]
This has been fixed. Run `npm update` or manually bump the version in package.json to `"@shopify/app-cli-node-generator-helper": "^1.2.2"`! Let us know if list pages are causing any more issues.
