### ISSUE TITLE
Why use "ctx.res" (node response object) instead of "ctx.response" (koa Response object)

### ISSUE THREAD

**Issue by theptrk** [Shopify/shopify-app-node#491]
# Issue summary

This shouldn't actually cause any issues but I found the use of `ctx.res` is not supported by Koa. 
Based on the docs:

`Bypassing Koa's response handling is not supported. Avoid using the following node properties:`

https://github.com/koajs/koa/blob/master/docs/api/context.md#ctxres

This is the code in `/server/server.js`
```
  router.get("(.*)", verifyRequest(), async (ctx) => {
    await handle(ctx.req, ctx.res);
    ctx.respond = false;
    ctx.res.statusCode = 200;
  });
```

Wondering if this is for a special purpose

**Comment by paulomarg** [comment]
That's interesting, thank you for reporting it. We will look into using the supported object!

**Comment by tyzion** [comment]
I know it's pretty old, but it's still there when you create a node app with Shopify cli.
I'm very new to Shopify app development and I was a little confused about that, during the app development.

**Comment by JaKXz** [comment]
This has been addressed with the overhaul moving to Express. Please open new issues with bugs found or discussions with your questions, thanks!
