### ISSUE TITLE
Access  Token

### ISSUE THREAD

**Issue by CBDozer** [Shopify/shopify-app-node#518]
Not an actual issue.

How do I store the accessToken so that I can use it to call shopify api from my public app?

[server/server.js](https://github.com/Shopify/shopify-app-node/blob/master/server/server.js)
```
32  server.use(
33    createShopifyAuth({
34      apiKey: SHOPIFY_API_KEY,
35      secret: SHOPIFY_API_SECRET,
36      scopes: [SCOPES],
37
38      async afterAuth(ctx) {
39        // Access token and shop available in ctx.state.shopify
40        const { shop } = ctx.state.shopify;
41
42        // Redirect to app with shop parameter upon auth
43        ctx.redirect(`/?shop=${shop}`);
44      },
45    })
```

**Comment by paulomarg** [comment]
Once you complete OAuth, the access token will be available in two ways:
- Inside `afterAuth`, you'll be able to access it in `ctx.state.shopify.accessToken`
- On other requests, it will be in `ctx.session.accessToken`

Hope this helps!

Also, quick note: usually, Github issues should be used for tracking actual bugs in the code. We recommend posting support questions in our [Community forums](https://community.shopify.com/c/App-Partner-Platform/ct-p/appdev) where you'll get more complete answers.

**Comment by CBDozer** [comment]
Alright thanks.

I also found more resource @ https://shopify.dev/tutorials/build-a-shopify-app-with-node-and-react/fetch-data-with-apollo
