### ISSUE TITLE
New routes created using the navigation don't work

### ISSUE THREAD

**Issue by icaroNZ** [Shopify/shopify-app-node#564]
# Issue summary

I create an app using the CLI, after that, I create a new page, so now I have on my page folder 3 files.
```
_app.js
index.js
new.js
```
On the Shopify app page, I create 2 navigation items index and new and pointed to 
```
http://.../index
http://.../new
```
A sample application can be found [here - https://github.com/icaroNZ/simple-shopify-app](https://github.com/icaroNZ/simple-shopify-app) 

## Expected behavior

When I go back on the app, I should be able to see the index page and the new page.

## Actual behavior

The index page works fine, and once I try to access the new page, I get redirected to the index page.

## Steps to reproduce the problem

Create a new app using the CLI
Create a new file inside the page called new.js
Copy the content of the index.js page into new.js (renaming the function and export)
Create 2 navigation items redirecting to index and new
GO to the app and try to navigate to the new page
 
## Where I think is the problem

The problem seems to be here, 

```
  server.use(
    createShopifyAuth({
      async afterAuth(ctx) { // <- afterAuth seems to be always call
        // Access token and shop available in ctx.state.shopify
        const { shop, accessToken, scope } = ctx.state.shopify;
        ACTIVE_SHOPIFY_SHOPS[shop] = scope;

        const response = await Shopify.Webhooks.Registry.register({
          shop,
          accessToken,
          path: "/webhooks",
          topic: "APP_UNINSTALLED",
          webhookHandler: async (topic, shop, body) =>
            delete ACTIVE_SHOPIFY_SHOPS[shop],
        });

        if (!response.success) {
          console.log(
            `Failed to register APP_UNINSTALLED webhook: ${response.result}`
          );
        }

        // Redirect to app with shop parameter upon auth
        ctx.redirect(`/?shop=${shop}`);  // <- always get redirect to the shop aka index page
      },
    })
  );
```

Should the `afterAuth` be called every time even when the app is already authenticated?
If so how can I avoid redirection or redirect to the correct page?

## Things that I try

Check if there is a `accessToken` and if there is call `next() `and `return` (didn't work)
```
if ( accessToken ) {
  return next();
}
```

I also try to look on the ctx for the address we want to go without lucky.

## Specifications

- Browser: Chrome
- Device: Macbook pro
- Operating System: macOS

**Comment by ilugobayo** [comment]
Did you solve this problem?

**Comment by tmstn** [comment]
@ilugobayo I solved this problem by avoiding the `router.get("(.*)", verifyRequest(), handleRequest);` catch all route and instead having fixed routes for each page. It is an annoyance and should be unnecessary but it works. ​

In my server.js file I removed:

```js
  router.get("/", async (ctx) => {
    const shop = ctx.query.shop;

    // This shop hasn't been seen yet, go through OAuth to create a session
    if (ACTIVE_SHOPIFY_SHOPS[shop] === undefined) {
      ctx.redirect(`/auth?shop=${shop}`);
    } else {
      await handleRequest(ctx);
    }
  });
```

And added the following:

```js
  const routeHandler = async (ctx) => {
    const shop = ctx.query.shop;

    // This shop hasn't been seen yet, go through OAuth to create a session
    if (ACTIVE_SHOPIFY_SHOPS[shop] === undefined) {
      ctx.redirect(`/auth?shop=${shop}`);
    } else {
      await handleRequest(ctx);
    }
  };

  router.get("/", async (ctx) => routeHandler(ctx));
  router.get("/reports", async (ctx) => routeHandler(ctx));
  router.get("/annotated-layout", async (ctx) => routeHandler(ctx));
```
