### ISSUE TITLE
"Token must be service access."

### ISSUE THREAD

**Issue by SerhiDi** [Shopify/shopify-app-node#603]
Nodejs simple app.

Get "Token must be service access." error when run request: `GET /admin/api/2021-01/storefront_access_tokens.json`.
App in the sales channel.
scopes: unauthenticated_read_product_listings,unauthenticated_read_product_tags

I found this:
https://community.shopify.com/c/Shopify-APIs-SDKs/Error-quot-Token-must-be-service-access-quot-when-creating-a/td-p/571151

But I don't understand how I can use these cases in this Nodejs App boilerplate.
Shopify contains this error message in API response but doesn't have any reasonable information to resolve it.

**Comment by paulomarg** [comment]
That error comes from the API itself, so unfortunately we can't really change it in the library.

Are you using an online token to run that query? You can only manage storefront access tokens when using an offline token.

**Comment by SerhiDi** [comment]
I added  `accessMode: 'offline'` to `createShopifyAuth` inside `server.js`.
All working now.

**Comment by paulomarg** [comment]
Glad to hear it's working! Please make sure that requests using `verifyRequest` are also updated to `accessMode: 'offline'` so they don't break.

I'll go ahead and close this issue.

**Comment by EarthlingDavey** [comment]
@SerhiDi hi, I found your solution by chance. do you know, is this documented anywhere? 

And, is it still working ok for you?
