### ISSUE TITLE
Url doesn't work!

### ISSUE THREAD

**Issue by bbogdan2020** [Shopify/shopify-app-node#632]
# Issue summary

When use @shopify/polaris component all the components with url doesn't work.
e.g: Page with breadcrumbs doesn't redirect to url
e.g2: Button with url don't go to url.

## Expected behavior

Go to the page from url

## Actual behavior

Go to  white page or return an error with "shopify origin doesn't exist"

## Steps to reproduce the problem

Make a second page name settings with the following code and will observe just the Link from next redirect to root page
```
import React from 'react';
import { Page, Button } from '@shopify/polaris'
import Link from 'next/link'
const Settings = () => {
  return (
    <Page
        breadcrumbs={[{ content: "Dashboard", url: "/" }]}
        title="Settings"
        primaryAction={{
          content: "Save",
          
        }}
      >
        <Link href="/">
        Page under construction!!!
        </Link>
        <br></br>
        <Button primary url='/'>
          Go to dashboard
        </Button>
      </Page>
  )
}

export default Settings;

```

## Reduced test case

The best way to get your bug fixed is to provide a reduced test case.

## Specifications

All the browser.

**Comment by kojo-shopify** [comment]
Hey @bbogdan2020, Thanks for raising this. I'm taking a look at this now. I've also edited the issue to format the code properly.

**Comment by kojo-shopify** [comment]
@bbogdan2020 can you clarify how you are routing to your `settings` page? Did you add a route in your `server.js` or are you using the `ClientRouter` polaris component?

**Comment by kojo-shopify** [comment]
Thanks for clarifying @bbogdan2020, I think understand now. Generally speaking, we recommend using [`@shopify/app-bridge-react` components](https://shopify.dev/tools/app-bridge)  over Polaris components when available. In your case, using the [`Titlebar` component](https://shopify.dev/tools/app-bridge/react-components/titlebar) for breadcrumbs and your primary action should work as is.

The reason being that Polaris components are designed for a broader general use case, whereas the App Bridge components are designed for Embedded Apps. For that reason, I would also recommend using `Link` for navigation, and only using the `Button` for styling or actions like form submissions.

Taking all that into account, the code you posted above would look something like this:

```js
import React from 'react';
import { Page, Button } from '@shopify/polaris';
import { TitleBar } from '@shopify/app-bridge-react';

import Link from 'next/link'

const Settings = () => {
  return (
    <Page>
      <TitleBar
        breadcrumbs={[{ content: "Dashboard", url: "/" }]}
        title="Settings"
        primaryAction={{
          content: "Save",   
        }}
      />
      
      <Link href="/">
        Page under construction!!!
      </Link>
      
      <br></br>
    <Link href="/">
       <Button primary>
         Go to dashboard
       </Button>
      </Link>
    </Page>
  )
}

export default Settings;

```

Let me know if that helps you solve your issue

**Comment by bbogdan2020** [comment]
Thank. I will close the issue because can be solve with link component.
