### ISSUE TITLE
Getting undefined for environment variable at front end.

### ISSUE THREAD

**Issue by swanil009** [Shopify/shopify-app-node#643]
# Issue summary

Not able to access the environment variable at frontend.
In the .env file I've defined a variable in below format

APP_CODE=3
SHOPIFY_API_APP_CODE=3
REACT_APP_APP_CODE=3

but non of the constant is accessable at front end. It's giving undefined in the frontend js files.

Trying to access as 
console.log('app code check ', process.env.SHOPIFY_API_APP_CODE);

## Expected behavior

get the defined constant value.

Any Help ?

**Comment by arnau-rius** [comment]
Probably you need to tell _webpack_ what env variables you want to load. 
There is already the `API_KEY` environment variable loaded, in the starter code: https://github.com/Shopify/shopify-app-node/blob/master/next.config.js#L8. So you just need to add here the env variables that your frontend will need.

**Comment by swanil009** [comment]
> Probably you need to tell _webpack_ what env variables you want to load.
> There is already the `API_KEY` environment variable loaded, in the starter code: https://github.com/Shopify/shopify-app-node/blob/master/next.config.js#L8. So you just need to add here the env variables that your frontend will need.

Yes it works for me.. Thankyou.. :)

**Comment by paulomarg** [comment]
Thanks for responding @arnau-rius ! I'll go ahead and close this since it's solved.
