### ISSUE TITLE
Did you use SHOP variable in .env.example

### ISSUE THREAD

**Issue by NoharaMasato** [Shopify/shopify-app-node#645]
# Issue summary

I guess this app does not use SHOP environemt variable defined [here](https://github.com/Shopify/shopify-app-node/blob/922ec7f8a62d7601e2caa27d34e5b803d257cef4/.env.example#L4). Thanks.

**Comment by maruffahmed** [comment]
This **SHOP** variable in the `.env` file is not using anywhere in the code. But if you use Shopify CLI sometimes you have to run `shopify node open` command to see the app install URL. This **SHOP** variable helps to generate that URL. 

With SHOP variable Example `https://{TUNNEL_URL}:auth?shop={YOUR_SHOP}` 
Without SHOP variable Example `https://{TUNNEL_URL}:auth?shop=`

**Comment by NoharaMasato** [comment]
I understand!. Thanks for your answer.
