### ISSUE TITLE
Intellisense, prettier not working with this repo?

### ISSUE THREAD

**Issue by hjf** [Shopify/shopify-app-node#656]
# Issue summary

I'm having a very strange problem. I use VS Code and all my projects work fine with Prettier and Intellisense. Except this repo, where for some reason I only get syntax highlighting, but nothing else. Not even red lines on blatant syntax errors.

I've checked all I could think of and I can't find a solution. Am I missing a plugin for VS code or something like that?

## Expected behavior

Syntax checks and formatting should work like in any other project.

## Actual behavior

Syntax checks and formatting don't work

## Steps to reproduce the problem

1. Create app with ```shopify node create```
2. Open app with VS Code
3. syntax check don't work

## Specifications

- Browser: N/A
- Device: N/A
- Operating System: Windows

**Comment by JaKXz** [comment]
Please give the new template a shot if you can and open new issues with bugs or discussions with questions, it should have prettier set up for you. Thanks!
