### ISSUE TITLE
Module not found: Can't resolve 'store-js'

### ISSUE THREAD

**Issue by Code-creators-dev-team-iqmerchant** [Shopify/shopify-app-node#658]
# Issue summary

import store from store-js does not work, errors, cannot find store-js

## Expected behavior

the store-js should be present

## Actual behavior

node errors, as store-js is missing

Tip: include an error message (in a `<details></details>` tag) if your issue is related to an error

## Steps to reproduce the problem

Build app and see node error logs

## Reduced test case

include store-js and see if node errors out

## Specifications

- Browser: Node 
- Device: Server
- Operating System: Ubuntu 20.04 LTS
Logs:
 Error - ./pages/components/ResourceList.js:11:0
┃ Module not found: Can't resolve 'store-js'
┃    9 |   Thumbnail,
┃   10 | } from '@shopify/polaris';
┃ > 11 | import store from 'store-js';
┃   12 | import { Redirect } from '@shopify/app-bridge/actions';
┃   13 | import { Context } from '@shopify/app-bridge-react';
┃   14 | import ApplyRandomPrices from './ApplyRandomPrices';
┃

**Comment by Yuri-Karpenko** [comment]
I have the exact same issue, but on MacOS.
