### ISSUE TITLE
Is the branch "sample_app_updates" safe to use? 

### ISSUE THREAD

**Issue by PurplePineapple123** [Shopify/shopify-app-node#681]
[This](https://github.com/Shopify/shopify-app-node/commit/53dfbfda7e867c8ac53182b78099c46b8a50b110#comments) thread mentions that the Nextjs removal update was temporarily rolled back. The "sample_app_updates" branch was said to be updated with the removal of Nextjs. 

I'm working on a new project and would prefer to develop without Nextjs if possible. Can the "sample_app_updates" branch be used safely?

**Comment by paulomarg** [comment]
Hey @PurplePineapple123! Yes, you can use that branch for your app - we'll be re-merging that as soon as we've resolved the issues mentioned in the thread.

I'm closing this since it's not an actual issue with the library, but please feel free to report back if you have any problems.
