### ISSUE TITLE
It is not possible to build a basic app with this scafolded codebase without excessive digging

### ISSUE THREAD

**Issue by j-d-carmichael** [Shopify/shopify-app-node#691]
# Issue summary

The docs are poor.

As a new developer to shopify the 1st task is to be able to put together a production level CRUD style app complete with authentication between shopify and the built app.

This is basically impossible without excessive stackoverflow, and github issue digging.

## Expected behavior

See a simple to understand best practice architecture diagram and then simple to follow documentation to be able to be up and running.

## Actual behavior

The docs are disjointed, there are no architectural diagrams explaining how the shopify -> iframe -> react app -> api -> shopify should be. A series of lucky guesses resulted in a completed app. There is not even a link from this code base to the related docs about the code this node-app is all using. Considering how big shopify is, the number of adverts they run for engineers you would have thought something as trivial as good docs would not be an issue.

**Comment by mexicantexan** [comment]
@j-d-carmichael Quick question, I keep getting OAuth whitelisted errors, didn't know what params you ended up using in your app-setup page? I'm using:

App Url:
https://1b9e-173-17-34-235.ngrok.io/  

Allowed redirection URL(s):
http://127.0.0.1:3456/  ##<- I realize yours would be different, mainly just seeing if I'm missing and redirect urls##
https://1b9e-173-17-34-235.ngrok.io/auth/callback

**Comment by mexicantexan** [comment]
Never mind ended up just reinstalling everything and it worked???? Idk

**Comment by j-d-carmichael** [comment]
You might want to take a look at this issue, my last comment:  https://github.com/Shopify/shopify-app-node/issues/690

**Comment by mexicantexan** [comment]
Yeah it's a bit of a rigamarole to get this repo moving, didn't realize @jono-allen had a repo up and running! Definitely going to take a look into it over the weekend :D

**Comment by teddyhwang** [comment]
thanks for the report. we've since updated the template to be much simpler to work with and have updated our [getting started tutorial](https://shopify.dev/apps/getting-started). we are actively working towards rapid, incremental improvements to the template moving forward so please do open another issue if you run into any problems.
