### ISSUE TITLE
Fast Refresh breaks AppBridge context

### ISSUE THREAD

**Issue by lmartins** [Shopify/shopify-app-node#719]
# Issue summary
I've setup this app using the CLI, and have since changed it slightly to use a custom session driver to persist session data into a database rather than using the in-memory approach it comes with by default.

After that I've tried creating additional pages on this app, using NextJS file based routes, using the Shopify's `RoutePropagator` component to make the embedded app aware of NextJS' route changes.

With this setup, I can work on the `index.js` page without any issues. It refreshes normally and I'm still able to do GraphQL queries. However on any other page route, each time I save a change I get the following message:

```
About to perform a full refresh
Fast Refresh will perform a full reload when you edit a file that is imported by modules outside of the React rendering tree. It is also possible the parent component of the component you edited is a class component, which disables Fast Refresh. Fast Refresh requires at least one parent function component in your React tree.

You can find more information in the related error below:
```
The trace that comes with this message is as follows:
```
Error: Aborted because ./pages/products.jsx is not accepted
Update propagation: ./pages/products.jsx -> ./node_modules/next/dist/build/webpack/loaders/next-client-pages-loader.js?page=%2Fproducts&absolutePagePath=%2FUsers%2Fluismartins%2FSites%2Flab%2Fshopappnodetest%2Fpages%2Fproducts.jsx!
    at applyHandler (https://382a-188-81-999-2.ngrok.io/_next/static/chunks/webpack.js?ts=1645272045498:852:31)
    at https://382a-188-81-999-2.ngrok.io/_next/static/chunks/webpack.js?ts=1645272045498:536:21
    at Array.map (<anonymous>)
```  

This message then allows to manually trigger the reload, which in turn results on the following error:

```
Unhandled Runtime Error
AppBridgeError: APP::ERROR::INVALID_CONFIG: host must be provided
```

The browser console shows:
```
AppBridgeError {name: 'AppBridgeError', message: 'APP::ERROR::INVALID_CONFIG: host must be provided', action: undefined, type: 'APP::ERROR::INVALID_CONFIG', stack: 'AppBridgeError: APP::ERROR::INVALID_CONFIG: host must be provided'}
```

The host is passed to App Bridge `Provider` via `getInitialProps`.

Is this expected behavior?

**Comment by Michael-Gibbons** [comment]
@lmartins Great question, client side routing is very tricky and unintuitive imo. I believe the issue you're having is because you're not using next's routing method so the context isn't being passed which is giving you that auth error. Here is how I implemented it, 

```js
class MyApp extends App {
  render() {
    const { Component, pageProps, host } = this.props;
    return (
      <AppProvider i18n={translations}>
        <Provider
          config={{
            apiKey: API_KEY,
            host: host,
            forceRedirect: true,
          }}
        >
          <ClientRouter /> // <--- this
          <RoutePropagator /> <-- and this
          <MyProvider Component={Component} {...pageProps} />
        </Provider>
      </AppProvider>
    );
  }
```

```js
//clientRouter.js
import { withRouter } from "next/router";
import { ClientRouter as AppBridgeClientRouter } from "@shopify/app-bridge-react";

function ClientRouter(props) {
  const { router } = props;
  return <AppBridgeClientRouter history={router} />;
}

export default withRouter(ClientRouter);

```

```js
// routePropagator.js
import {
  useAppBridge,
  RoutePropagator as ShopifyRoutePropagator,
} from "@shopify/app-bridge-react";
import { Loading, Frame } from "@shopify/polaris";
import { useRouter } from "next/router";
import { useState, useEffect } from "react";

const RoutePropagator = () => {
  const router = useRouter();
  const { route } = router;
  const app = useAppBridge();

  const [loading, setLoading] = useState(false);

  useEffect(() => {
    router.events.on("routeChangeStart", () => {
      setLoading(true);
    });
    router.events.on("routeChangeComplete", () => {
      setLoading(false);
    });
    router.events.on("routeChangeError", () => {
      setLoading(false);
    });
  }, []);

  if (loading) {
    return (
      <Frame>
        <Loading></Loading>
      </Frame>
    );
  }
  return app && route ? <ShopifyRoutePropagator location={route} /> : null;
};

export default RoutePropagator;

```

So what this does is basically handles the routing using nextJS, then it passes the buck to react to actually update the dom.

Hope that helps, let me know if you have any questions.

**Comment by lmartins** [comment]
@Michael-Gibbons  thank you so much for the detailed explanation. I was using the `Link` component from NextJS but I've swapped to your solution.

Unfortunately it sill behaves the same, every time I make a change to a page, it is any other page than `index.js` AND I'm currently on that page, the app will crash. For some reason the `Provider` from `@shopify/app-bridge-react` loses context and is unable to read from the class props.

This is coming from the `_app.js` component that is still very close to what Shopify suggests:
```js
class MyApp extends App {
  render() {
    const { Component, pageProps, host } = this.props;
    return (
      <AppProvider i18n={translations}>
        <Provider
          config={{
            apiKey: API_KEY,
            host: host,
            forceRedirect: true,
          }}
        >
          <ClientRouter />
          <RoutePropagator />
          <DatabaseProvider Component={Component} {...pageProps} />
        </Provider>
      </AppProvider>
    );
  }
}

MyApp.getInitialProps = async ({ ctx }) => {
  return {
    shop: ctx.query.shop,
    host: ctx.query.host,
  };
};

export default MyApp;
```

The sense that I'm getting is that the Fast Refresh process is trying to replace the App Bridge Provider, but in doing so it stops being able to access the variables that are loaded server-side by NextJS with the `getInitialProps` function. If that is indeed the case, this is super confusing as this is pretty much the Node CLI's boilerplate structure.

**Comment by Michael-Gibbons** [comment]
You wouldn't happen to be exporting any functional components as arrow functions would you? Exporting arrow functions would lose context. 

Also, the files names in your `pages` directory, are they lowercase? Uppercase file names aren't supported by fast refresh I believe so `pages/Orders.js` wouldn't work but `pages/orders.js` would

**Comment by lmartins** [comment]
Oh that's a good point @Michael-Gibbons, thank you!
I was indeed declaring the `products` page as an arrow function. Fixed that, sadly same behavior persists. I get from your comments that what I'm seeing is not the default experience with a typical install from the CLI command, so I'll keep digging to try get clarity on this. Thank you so much for your suggestions though.

**Comment by lmartins** [comment]
Yeah, I've looked into those earlier. I think I'll have to test things out on a fresh vanilla app install and retrace my steps. Hopefully that will give me something. I'll update this once I find what is causing this.

Again, thanks so much @Michael-Gibbons

**Comment by lmartins** [comment]
For anyone who may encounter this in the future, I now believe that the issue on my case was due to mismatched Apollo packages. 

I was using the `@apollo/client` package, rather than `react-apollo` and that I now think was causing the process to break in unexpected ways.

**Comment by lmartins** [comment]
@Michael-Gibbons I did quite a bit of experimentation with that `authenticatedFetch` function, so maybe that was it. For now I'll keep what was "prescribed" by the CLI install.

I can't thank you enough for all the help with this. Thank you!
