### ISSUE TITLE
Failed to read the 'sessionStorage' property from 'Window': Access is denied for this document.

### ISSUE THREAD

**Issue by ph33nx** [Shopify/shopify-app-node#723]
# Issue summary

Unhandled Runtime Error
SecurityError: Failed to read the 'sessionStorage' property from 'Window': Access is denied for this document.

## Expected behavior

Changes made in nextjs should be hot reloaded.

## Actual behavior

Nextjs showed an error as soon as the changes were saved in pages/index.js

Tip: include an error message (in a `<details></details>` tag) if your issue is related to an error
<details>
Unhandled Runtime Error
SecurityError: Failed to read the 'sessionStorage' property from 'Window': Access is denied for this document.
</details>

## Steps to reproduce the problem

1. install the app using "shopify app create node"
2. run "shopify app serve"
3. change "Shopify app with Node" text in pages/index.js

## Specifications

- Browser: Chrome 98.0.4758.102
- Device: Desktop
- Operating System: Tested on both Windows 10 / macOS Monterey

**Comment by Michael-Gibbons** [comment]
This sounds like you have a chrome extension blocking scripts on your page. I am unable to replicate your issue

**Comment by ph33nx** [comment]
Had to select "Allow all cookies" under Chrome Settings > Security & Privacy > Content > Cookies and site data > Allow all cookies. Previously had "Block third-party cookies" selected. I don't know if it's the default option for newer versions of chrome or if it was just set that way for me.

![image](https://user-images.githubusercontent.com/19635345/158026702-1386f40e-c777-49d4-bf0a-b56c1fa1a8b9.png)
