### ISSUE TITLE
Apollo Client still out of date after new codebase

### ISSUE THREAD

**Issue by kuipou** [Shopify/shopify-app-node#733]
# Issue summary
I've just ran a new test app to try out the new code for appnode and I had to run ncu u as there a lot package out of date.
Apollo Client as been updated to use the @apollo/client package instead of boost 

## Expected behavior

What do you think should happen?

## Actual behavior

What actually happens?

Tip: include an error message (in a `<details></details>` tag) if your issue is related to an error

## Steps to reproduce the problem

1. shopify app create node 
2. npx npx npm-check-updates -u

## Reduced test case
the console output:
```
npx npm-check-updates -u
Need to install the following packages:
  npm-check-updates
Ok to proceed? (y) y
Upgrading /home/kip/site/temp/test2/package.json
[====================] 38/38 100%

 @babel/core                       7.12.10  →    7.17.5     
 @babel/preset-env                ^7.12.11  →  ^7.16.11     
 @babel/register                  ^7.12.10  →   ^7.17.0     
 @shopify/app-bridge-react          ^2.0.6  →   ^2.0.17     
 @shopify/app-bridge-utils          ^2.0.6  →   ^2.0.17     
 @shopify/polaris                   ^6.2.0  →    ^9.2.0     
 dotenv                             ^8.2.0  →   ^16.0.0     
 graphql                           ^14.5.8  →   ^16.3.0     
 koa                               ^2.13.1  →   ^2.13.4     
 koa-router                        ^10.0.0  →   ^10.1.1     
 koa-session                        ^6.1.0  →    ^6.2.0     
 node-fetch                         ^2.6.7  →    ^3.2.2     
 react-apollo                       ^3.1.3  →    ^3.1.5     
 webpack                           ^4.44.1  →   ^5.70.0     
 @babel/plugin-transform-runtime  ^7.12.10  →   ^7.17.0     
 @babel/preset-stage-3              ^7.0.0  →    ^7.8.3     
 babel-jest                         26.6.3  →    27.5.1     
 eslint                             ^8.9.0  →   ^8.10.0     
 eslint-config-next               ^12.0.10  →   ^12.1.0     
 husky                              ^4.3.6  →    ^7.0.4     
 jest                               26.6.3  →    27.5.1     
 lint-staged                       ^10.5.4  →   ^12.3.5     
 nodemon                            ^2.0.7  →   ^2.0.15     
 prettier                            2.2.1  →     2.5.1     
 react-test-renderer               16.14.0  →    17.0.2     

Run npm install to install new versions.
```

## Specifications

- Browser: none
- Device: console
- Operating System: console

**Comment by Michael-Gibbons** [comment]
I'm not entirely sure what you're trying to do, if you're referring to the express build, the new build isn't accessible from the cli yet because it isn't merged into master. So you're still seeing the nextjs build as you can see by the package.json using koa

**Comment by Michael-Gibbons** [comment]
Are you talking about these dependency updates? 
![image](https://user-images.githubusercontent.com/13829417/157935894-2e19cc4e-7baa-4f99-91ee-58c588e2bf15.png)

if so this does not relate to the express branch, these are automated updates which will not cause version errors and remain backward compatible, so this is still relating to the nextjs codebase.

**Comment by Michael-Gibbons** [comment]
For instructions on using the experimental branch, read the readme or see #725

**Comment by teddyhwang** [comment]
thanks for the report - we've since updated the template. please open a new issue if you're still seeing problems with packages.
